FROM google/cloud-sdk:alpine

MAINTAINER James Smith <james.smith@heig-vd.ch>



RUN ["env"]


# Cmd to lunch in the kubernetes cluster (need to added by script or copy/paste)
# CMD ["sh", "./tmp/kubectlCmd.sh"]

